project:
  type: website
  output-dir: _site

website:
  title: "Robert Shaw"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html
      - text: Code & projects
        href: code-projects.html

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
    include-in-header:
      - _font.html
