project:
  type: website
  output-dir: _site
  resources:
    - images/**
    - videos/**

website:
  title: "Robert Shaw"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: About
        href: about.html
      - text: Code & projects
        href: code-projects.html
      - text: Hobbies & interests
        href: hobbies-interests.html
      - text: My CV
        href: CV_ROBERT_SHAW.pdf

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
    include-in-header:
      - _font.html
